from UI import *
from controller import *
from repository import *

studentRepo=PickleRepository("studentRepo.txt")
assignmentRepo=PickleRepository("assignmentRepo.txt")
gradeRepo=PickleRepository("gradeRepo.txt")
studentAssignmentsRepo=Repository()
studentController=Controller(studentRepo)
assignmentController=Controller(assignmentRepo)
gradeController=Controller(gradeRepo)
studentAssignmentsController=Controller(studentAssignmentsRepo)
'''
studentController.add(Student(1,'Marian',1))
studentController.add(Student(2,'George',1))
studentController.add(Student(3,'Raluca',2))
studentController.add(Student(4,'Georgiana',3))
studentController.add(Student(5,'Lucian',3))
studentController.add(Student(6,'Vasile',2))
studentController.add(Student(7,'Maria',1))
studentController.add(Student(8,'Veronica',3))
studentController.add(Student(9,'Sonia',3))
studentController.add(Student(10,'Lucica',2))
studentController.add(Student(11,'Rebeca',1))
studentController.add(Student(12,'Mircea',2))
studentController.add(Student(13,'Janina',4))
assignmentController.add(Assignment(1,'Solve the problem','7.7.2017'))
assignmentController.add(Assignment(2,'Solve the problem','7.7.2017'))
assignmentController.add(Assignment(3,'Solve the problem','7.7.2017'))
assignmentController.add(Assignment(4,'Solve the problem','7.7.2017'))
assignmentController.add(Assignment(5,'Solve the problem','7.7.2017'))
assignmentController.add(Assignment(6,'Solve the problem','7.7.2017'))
assignmentController.add(Assignment(7,'Solve the problem','7.7.2017'))
assignmentController.add(Assignment(8,'Solve the problem','7.7.2017'))
assignmentController.add(Assignment(9,'Solve the problem','7.7.2017'))
assignmentController.add(Assignment(10,'Solve the problem','7.7.2017'))
assignmentController.add(Assignment(11,'Solve the problem','7.7.2017'))
assignmentController.add(Assignment(12,'Solve the problem','7.7.2017'))
assignmentController.add(Assignment(13,'Solve the problem','7.7.2017'))
'''
ui=UI(studentController,assignmentController,gradeController,studentAssignmentsController)
ui.start()
